language: node_js
node_js:
- "14.9.0"
dist: trusty

branches:
  only:
  - master
  
notifications:
  email: false
  
cache:
  directories:
    - ./node_modules
    
install:
  - npm install

script:
  - npm run test-headless
  
before-deploy:
  - ng build --prod
  - cp dist/IP3/index.html dist/IP3/404.html
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/trivia
  on:
    branch: master

