language: node_js
node_js:
- "14.9.0"
dist: trusty

branches:
  only:
  - master
cache:
  directories:
    - ./node_modules
    
install:
  - npm install

script:
  - npm run test-headless
  - ng build --prod
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/Trivia
  on:
    branch: master

