language: node_js
node_js:
- "14.9.0"
dist: trusty

branches:
  only:
  - master
  
notifications:
  email: false
  
cache:
  directories:
    - ./node_modules
    
install:
  - npm install

script:
  - npm run test-headless
